### PR TITLE
Use level iterator stream

### PR DESCRIPTION
**Pull request by juliangruber**
I'm not happy with the implementation yet, so looking for early feedback.

### CODE REVIEW

**Comment by juliangruber** [comment]
i'm happy with the implementation now, just need to merge https://github.com/Level/codec/pull/5

**Comment by juliangruber** [comment]
and squash obviously

**Comment by juliangruber** [comment]
cool, reviews please :) i know @ralphtheninja already :+1:ed an old version of this pr

**Comment by ralphtheninja** [comment]
What's up with the tests failing?

**Comment by jcrugzz** [comment]
does it still need the new version of deferredleveldown to be published?

**Comment by juliangruber** [comment]
aside from the tests failing, this currenlty is a 50% performance degression. i'm looking at the tests now.

**Comment by juliangruber** [comment]
weirdly this test does not fail on master with the same node version

**Comment by juliangruber** [comment]
and for me it only fails in the deferred-open-test

**Comment by juliangruber** [comment]
the test failure is now happening in all node versions, most of the time. inserting a console.log() sometimes helps.

can someone help me debug this? like, how do i get stack traces etc.

```
node: ../deps/leveldb/leveldb-1.17.0/db/version_set.cc:789: leveldb::VersionSet::~VersionSet(): Assertion `dummy_versions_.next_ == &dummy_versions_' failed.
```

**Comment by juliangruber** [comment]
the real fix should go here: https://github.com/Level/leveldown/pull/169

**Comment by juliangruber** [comment]
and that fixes it :)

**Comment by ralphtheninja** [comment]
lgtm

**Comment by juliangruber** [comment]
i'll update leveldown, verify benchmarks are ok and then squash and merge

**Comment by juliangruber** [comment]
`test/benchmark/stream-bench.js` on __master__:

```
Filled source! Took 3134ms, reading data now...
Done! Took 1668ms with {}
Done! Took 1682ms with {"keys":true}
Done! Took 1742ms with {"values":true}
Done! Took 1571ms with {"keys":true,"values":true}
Done! Took 1841ms with {}
Done! Took 1439ms with {"keys":true}
Done! Took 1392ms with {"values":true}
Done! Took 1488ms with {"keys":true,"values":true}
Done! Took 1491ms with {}
Done! Took 1504ms with {"keys":true}
Done! Took 1474ms with {"values":true}
Done! Took 1494ms with {"keys":true,"values":true}
```

on this branch:

```
Done! Took 1500ms with {}
Done! Took 1423ms with {"keys":true}
Done! Took 1334ms with {"values":true}
Done! Took 1340ms with {"keys":true,"values":true}
Done! Took 1344ms with {}
Done! Took 1333ms with {"keys":true}
Done! Took 1546ms with {"values":true}
Done! Took 1477ms with {"keys":true,"values":true}
Done! Took 1368ms with {}
Done! Took 1325ms with {"keys":true}
Done! Took 1323ms with {"values":true}
Done! Took 1327ms with {"keys":true,"values":true}
```

So it's even faster now :) Btw I ran the master bench _after_ the one from this branch.

**Comment by ralphtheninja** [comment]
:sunglasses:

**Comment by ralphtheninja** [comment]
And here are the results from the Swedish jury:

```
Filled source! Took 1302ms, reading data now...
Done! Took 635ms with {}
Done! Took 569ms with {"keys":true}
Done! Took 540ms with {"values":true}
Done! Took 539ms with {"keys":true,"values":true}
Done! Took 540ms with {}
Done! Took 541ms with {"keys":true}
Done! Took 560ms with {"values":true}
Done! Took 571ms with {"keys":true,"values":true}
Done! Took 552ms with {}
Done! Took 527ms with {"keys":true}
Done! Took 528ms with {"values":true}
Done! Took 550ms with {"keys":true,"values":true}
```

**Comment by mcollina** [comment]
This is __GREAT__.

**Comment by juliangruber** [comment]
merged manually

**Pull request closed without merging**
