### PR TITLE
Maybe error sync

### PR DESCRIPTION
**Pull request by ralphtheninja**
`callback` is called within `maybeError()` before we even return the `promise`

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Should be enough to merge this to close https://github.com/Level/levelup/pull/458

**Comment by juliangruber** [comment]
have you tested this? i think it won't work because when we do `[callback,promise] = promisify()` we create a new `callback` reference, different from the one passed to `maybeError`. This means all calls to `maybeError` should go after creating the promise, right?

**Comment by ralphtheninja** [comment]
> have you tested this? i think it won't work because when we do [callback,promise] = promisify() we create a new callback reference, different from the one passed to maybeError. This means all calls to maybeError should go after creating the promise, right?

Nope. Hold off with this PR and let me write a test for it first. I might be wrong here.

**Comment by ralphtheninja** [comment]
Closing. Will make a new PR if I'm right :wink:

**Pull request closed without merging**
