### PR TITLE
esify lib code

### PR DESCRIPTION
**Pull request by aks-**
I have converted lib files to use es6 modules, left out levelup.js for now, because it would be kind of major bump. If we convert that into class, it would change how it's called hence changing api. Should I convert the test in the same PR?

### CODE REVIEW

**Comment by ralphtheninja** [comment]
This is already a major bump since we can't support node 4.

**Comment by aks-** [comment]
cool, will work on this next holiday

**Comment by ljharb** [comment]
@ralphtheninja why can't you support node 4? It's still LTS until April.

**Comment by ralphtheninja** [comment]
@ljharb With this change we can't support node 4 since it contains destructuring.

**Comment by ljharb** [comment]
Well sure, but the prudent course of action then is either to "not use destructuring", or to add babel (which i'd recommend).

**Comment by ralphtheninja** [comment]
> Well sure, but the prudent course of action then is either to "not use destructuring", or to add babel (which i'd recommend).

I agree :) I personally prefer to not use destructuring.

**Comment by ralphtheninja** [comment]
I think rewriting to use `class` rather than `prototype` is unnecessary. The prototype code works well and I'm worried this will have a performance effect.

Also, my point in not supporting node 4 was that we still want to support node 4. The solution is not to remove node 4 from travis, but rather to not use destructuring.

**Comment by ralphtheninja** [comment]
@vweevers This will be a problem testing on IE10, right?

**Comment by vweevers** [comment]
Yes. IMO we should just keep things as-is.

**Pull request closed without merging**
