### PR TITLE
change copyright year to 2012-2018

### PR DESCRIPTION
**Pull request by adityapurwa**
I changed the copyright year to 2012-2018, it will make the project feels fresh and occasionally maintained.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Thanks! However, there are more files that have the same copyright text that also need to be updated.

```
$ git grep 2017
CHANGELOG.md:## 2.0.0 @ October 2017
LICENSE.md:Copyright (c) 2012-2017 LevelUP contributors
README.md:Copyright &copy; 2012-2017 `levelup` [contributors](https://github.com/level/community#contributors).
lib/batch.js:/* Copyright (c) 2012-2017 LevelUP contributors
lib/levelup.js:/* Copyright (c) 2012-2017 LevelUP contributors
lib/promisify.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/argument-checking-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/batch-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/benchmarks/engines/index.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/benchmarks/engines/levelup-release.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/benchmarks/engines/levelup.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/benchmarks/engines/sqlite3.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/benchmarks/index.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/benchmarks/tests/index.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/binary-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/browserify-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/common.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/create-stream-vs-put-racecondition.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/data/browser-throws.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/data/browser-works.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/deferred-open-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/get-put-del-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/idempotent-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/index.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/init-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/inject-encoding-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/json-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/key-value-streams-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/leveldown-substitution-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/maybe-error-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/no-encoding-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/null-and-undefined-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/open-patchsafe-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/read-stream-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
test/snapshot-test.js:/* Copyright (c) 2012-2017 LevelUP contributors
```

**Comment by adityapurwa** [comment]
Awesome, working on it.

**Comment by adityapurwa** [comment]
I did not change the year on CHANGELOG.md, the year 2017 is related with the info below it and I dont think it should be changed.

**Comment by ralphtheninja** [comment]
> I did not change the year on CHANGELOG.md, the year 2017 is related with the info below it and I dont think it should be changed.

I was obviously wrong in doing `git grep 2017` but you got the gist of it at least.

**Comment by ralphtheninja** [comment]
Thanks! 😄

**Pull request merged**
