### PR TITLE
remove leveldown-substitution-test.js

### PR DESCRIPTION
**Pull request by ralphtheninja**
~~Closes https://github.com/Level/levelup/issues/550~~

### CODE REVIEW

**Comment by ralphtheninja** [comment]
I don't think we need to update `CHANGELOG` on each PR as long as we make sure to update it on each release. If we try to release often, it should be minimal work.

**Comment by vweevers** [comment]
Re https://github.com/Level/levelup/issues/549#issuecomment-365082569:

> I think we should remove the test using the internals of memdown. I don't see the point of it. The test is already doing db.createReadStream() and tests that entries is the same as expected.

I think you're right. The point of the test *used to be* that `levelup` would default to `leveldown` as backing store. So when swapping it for `memdown`, the test had to check not only that the `levelup` instance returned the right data but that this data was actually stored in memdown.

**Comment by vweevers** [comment]
Maybe we can just remove this file entirely.

**Comment by ralphtheninja** [comment]
Should be fine now.

**Comment by ralphtheninja** [comment]
https://travis-ci.org/Level/levelup/builds/340727414

**Pull request merged**
