### PR TITLE
Test seek() integration

### LINKED ISSUE #658: Add seek integration test
Once https://github.com/Level/memdown/pull/184 is released.

In `test/iterator-test.js`. It should test:

- [x] deferred, encoded seek
- [x] deferred, non-encoded seek
- [x] non-deferred, encoded seek
- [x] non-deferred, non-encoded seek

### PR DESCRIPTION
**Pull request by vweevers**
Closes #658.

### CODE REVIEW

**Comment by vweevers** [comment]
Test failure is unrelated; will be fixed by #662.

**Comment by vweevers** [comment]
Merging because it's only a test and I want to release `levelup`, `subleveldown` and `level-test` today.

**Comment by vweevers** [comment]
4.1.0

**Comment by MeirionHughes** [comment]
Sorry I didn't see the review request. Been running around all morning. :/

**Comment by vweevers** [comment]
No worries, I didn't give you any chance really. I suddenly picked up the pace and was comfortable enough about this to release without review.

Thanks for adding `seek()` across the board :)

**Pull request merged**
