### PR TITLE
V2

### PR DESCRIPTION
**Pull request by juliangruber**
This is a tracking pull request for v2, living in the `v2` branch.

The high level changes are:
- remove `#approximateSize()`, `.destroy()` and `.repair()` (have been deprecated in master)
- pass in a `leveldown` instead of a location: `var db = levelup(leveldown(location))`
- remove notion of `.errorIfExists` and `.createIfMissing`, those are backend specific

Thoughts before releasing this:
- do we want to get the logic for passing in backends in any open/closed state in as well?
- in general, do we want to get more features in? so far we've mostly been cleaning up and introducing breaking changes, people might not think it's worth upgrading. https://github.com/Level/levelup/pull/338 comes to mind

### CODE REVIEW

**Comment by mcollina** [comment]
IMHO we don't need to force updating this. It will just come after a while.

Many many projects are still in the 0.x line anyway.

**Comment by tejasmanohar** [comment]
Any idea on when v2 will be out stable? Is it safe to use the v2 branch?

**Comment by juliangruber** [comment]
@tejasmanohar can you tell us why you're interested in using v2 vs v1?

**Comment by tejasmanohar** [comment]
@juliangruber nothing in particular right now... unless there are new features being added :smile: - the features in the list are not too much of importance to me. was just curious, starting a new project w/ level (new to level, too)

**Comment by juliangruber** [comment]
@tejasmanohar gotcha. then you're most likely good to go with v1, v2 is likely cause you lots of incompatibility issues with the current ecosystem.

**Comment by ralphtheninja** [comment]
@juliangruber Mind creating a few issues and add to [`v2` milestone](https://github.com/Level/levelup/milestones)? Since `standard` is on master, it's probably easier to redo these changes instead of trying to rebase on top of master.

**Comment by juliangruber** [comment]
@ralphtheninja created some issues :) https://github.com/Level/levelup/milestone/1

**Pull request closed without merging**
