### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by vweevers**
Last bits and pieces of #456. Also see long descriptions of the commits.

### CODE REVIEW

**Comment by vweevers** [comment]
I'll squash.

**Comment by ralphtheninja** [comment]
I think after merging this + adding some tests we should be ready to release 2.0.0

**Comment by ralphtheninja** [comment]
@vweevers Feel like writing some tests? :smile: If not, I can do it.

**Comment by vweevers** [comment]
I'll take a stab, sure.

**Comment by vweevers** [comment]
What the. npm installs `deferred-leveldown @ 2.0.0`..

**Comment by vweevers** [comment]
Argh. I had a lockfile.

**Comment by ralphtheninja** [comment]
@vweevers You can put

```
package-lock = false
```

in `~/.npmrc`

**Comment by vweevers** [comment]
Very nice, thanks!

**Pull request merged**
