### PR TITLE
remove leveldown options

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/Level/levelup/issues/440
Closes https://github.com/Level/levelup/issues/366

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Removing `.sync` should probably be added to this same PR

**Comment by ralphtheninja** [comment]
@juliangruber I just saw something I missed when it comes to passing options on the the backend, e.g. these ones:

* `get` https://github.com/Level/levelup/blob/2.x/lib/levelup.js#L194
* `put` https://github.com/Level/levelup/blob/2.x/lib/levelup.js#L230
* `del` https://github.com/Level/levelup/blob/2.x/lib/levelup.js#L252
* `batch` https://github.com/Level/levelup/blob/2.x/lib/levelup.js#L280

**Comment by ralphtheninja** [comment]
Also, there's `.fillCache` property mentioned for `.createReadStream()`, https://github.com/Level/levelup/tree/2.x#dbcreatereadstreamoptions which also should be removed (from readme)? It's leveldb specific after all.

**Comment by juliangruber** [comment]
> Also, there's .fillCache property mentioned for .createReadStream(), https://github.com/Level/levelup/tree/2.x#dbcreatereadstreamoptions which also should be removed (from readme)? It's leveldb specific after all.

agreed :)

Awesome work so far!

**Pull request merged**
