### PR TITLE
Fixes a typo in the README.md

### PR DESCRIPTION
**Pull request by djchie**
Fixes spelling mistake from "initialise" to "initialize"

### CODE REVIEW

**Comment by brycebaril** [comment]
You say "mistake" I say "that's how @rvagg spells that word. https://en.wiktionary.org/wiki/initialise

**Comment by juliangruber** [comment]
i agree with @brycebaril

**Comment by juliangruber** [comment]
thanks for taking the time, @djchie!

**Comment by djchie** [comment]
Sorry about that! And anytime! @juliangruber

**Pull request closed without merging**
