### PR TITLE
update travis

### PR DESCRIPTION
**Pull request by ralphtheninja**

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@juliangruber Seems tests doesn't work well with node 6. Any idea what's going on? Something related to `approximateSize()`.

**Comment by juliangruber** [comment]
node 6 has non blocking stdio by default, I guess that's it. I'll add a commit to make it blocking for the tests (https://twitter.com/izs/status/732317861067153408)

**Comment by juliangruber** [comment]
actually, since this pr is based on your private repo, can you add that?

**Comment by ralphtheninja** [comment]
> actually, since this pr is based on your private repo, can you add that?

No problem!

**Comment by ralphtheninja** [comment]
@juliangruber Can't get it to work

**Comment by juliangruber** [comment]
it was actually the deprecation text being different. fixed via https://github.com/Level/levelup/commit/ab144aaab1d5e85297b617249b54557040f3584e

**Comment by ralphtheninja** [comment]
> it was actually the deprecation text being different. fixed via ab144aa

Ohh hehe. Nice catch!

**Comment by ralphtheninja** [comment]
1.3.2

**Pull request merged**
