### PR TITLE
merge 2.x into master, prepare for rc1

### PR DESCRIPTION
**Pull request by ralphtheninja**
Lets get this merged and release `rc1`.

@mcollina What's the preferred way of creating rc-releases? `npm version 2.0.0-rc1` and just `npm publish`?

### CODE REVIEW

**Comment by juliangruber** [comment]
you need to tag it, otherwise npm will consider it when installing `levelup@latest`:

```bash
$ npm version 2.0.0-rc1
$ npm publish --tag rc
```

for example

**Comment by juliangruber** [comment]
do we have a documented upgrade path yet?

**Comment by juliangruber** [comment]
also, should we land a leveldown where iterator methods return promises for this release too?

**Comment by ralphtheninja** [comment]
> do we have a documented upgrade path yet?

Nope, not yet.

> also, should we land a leveldown where iterator methods return promises for this release too?

Hmm never thought of that. Does that mean changes to `abstract-leveldown` as well?

@juliangruber When you say "this release", do you mean the final `2.0.0` version or _this_ `rc1` release? :)

**Comment by ralphtheninja** [comment]
We could wait with merging this PR a bit if you guys like and add some work to the README and _then_ merge.

**Comment by ralphtheninja** [comment]
> also, should we land a leveldown where iterator methods return promises for this release too?

I guess my main focus was to get `levelup@2.0.0` out the door as quick as possible, to avoid getting caught in perfection and ending up never releasing `2.0.0` because we find even more things we want to fix and change.

@juliangruber If you really feel it's necessary to hold this version for updates to `leveldown`, lets do it.

**Comment by juliangruber** [comment]
>> do we have a documented upgrade path yet?

> Nope, not yet. Would it be enough with an update to the CHANGELOG or should we have this section in the README?

I think the changelog is enough.

> also, should we land a leveldown where iterator methods return promises for this release too?

Oh, wait, no. We haven't talked about promise methods for leveldown yet, at all. Scratch this.

**Comment by ralphtheninja** [comment]
The upgrade guide has been added. We can work on tweaking the `README` and once we're happy with it and eventual bugs are found and solved we release the dragon.

Will merge this today and release `rc1` if no one is against.

**Pull request merged**
