### PR TITLE
Remove location argument

### PR DESCRIPTION
**Pull request by juliangruber**
this changes the api from

```js
var db = levelup(location, { db: leveldown })
```

to

```js
var db = levelup(leveldown(location))
```

this is for v2

### CODE REVIEW

**Comment by juliangruber** [comment]
a lot of code could be simplified, and documentation shortened. now there's only one way to create a db

**Comment by ralphtheninja** [comment]
:+1:

**Comment by juliangruber** [comment]
instead of relying on the package.json to check whether the leveldown is compatible, i added a check whether `.status` exists, which was added recently

**Comment by juliangruber** [comment]
can i get any other feedback?

**Comment by ralphtheninja** [comment]
cc @Level/owners

**Comment by rvagg** [comment]
:thumbsup: it's felt awkward since we split levelup into a generic frontend

**Comment by ralphtheninja** [comment]
w00t

**Comment by mafintosh** [comment]
this is great. :+1:

**Pull request merged**
