### PR TITLE
less restrictive on leveldown version

### PR DESCRIPTION
**Pull request by ralphtheninja**
See https://github.com/Level/levelup/issues/351

### CODE REVIEW

**Comment by juliangruber** [comment]
+1

**Comment by juliangruber** [comment]
shall we publish as 1.2.0? i consider more flexibility a feature

**Comment by ralphtheninja** [comment]
Sure :)

**Comment by ralphtheninja** [comment]
```
$ npm publish
+ levelup@1.2.0
```

**Pull request merged**
