### PR TITLE
Add airtap

### LINKED ISSUE #572: Add airtap
Pending new `abstract-leveldown` (published but there's an [npm issue](https://github.com/Level/leveldown/pull/479#issuecomment-390930122)) and https://github.com/Level/memdown/issues/157.

### PR DESCRIPTION
**Pull request by vweevers**
Closes #572.

### CODE REVIEW

**Comment by vweevers** [comment]
I've set the concurrency of Travis to 2 (also on `abstract-leveldown`). That allows Node.js builds to finish a little faster, while staying within Sauce Labs limits (Airtap's default concurrency of 5 * 2 = 10).

**Comment by vweevers** [comment]
IE10 has stalled. Looking into it.

**Comment by vweevers** [comment]
> IE10 has stalled. Looking into it.

Because `const` is still in `abstract-leveldown`. I got a bit confused with all the new releases.

First `abstract-leveldown@5` has to land in `deferred-leveldown`, `encoding-down` and `memdown`.

**Comment by vweevers** [comment]
@ralphtheninja are you working on the releases atm? can i take some?

**Comment by ralphtheninja** [comment]
> @ralphtheninja are you working on the releases atm? can i take some?

I'm working on releasing `rocksdb` and `leveldown`. I need to take small steps so I don't forget things. Please go ahead!

**Comment by vweevers** [comment]
Restarting tests. 🤞

**Comment by vweevers** [comment]
Rebased on master, to get new memdown.

**Comment by ralphtheninja** [comment]
> Rebased on master, to get new memdown.

:drum:

**Comment by ralphtheninja** [comment]
Browser tests on `levelup`!! :fireworks:

**Pull request merged**
